# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 699cd673d2c435c92f32ceaa31023a1c1cb438375694ddcca2a5ac25c2460d0774e7e1b073d67f30d6df3ec0f461cadd3d0a061dd76652a0b1e4f1e90a5d1dc9

test:
  secret_key_base: 9605ed9f7390db4d541f88adffe2718e828117f3a7ea5f4acf40145d3eaf7ae22f5f74b4024d3633fa5638d3ff0820ea6d52a27329d9191d1f57e9be856c9d9f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
